set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

setw -g status-style fg=colour255,bg=colour234

set -g status-left ""
set -g status-right ""
set -g status-justify right

setw -g window-status-current-format '#[bg=colour2,fg=colour255]#{?client_prefix,#[bg=colour3],} #I #W '
setw -g window-status-format '#[fg=colour242] #I #W '

set -g base-index 1

set-option -g mouse on